### PR TITLE
Update to NestJS 7

### PR DESCRIPTION
**Pull request by auscompgeek**
This bumps to nest-raven@7, which makes the `@nestjs/graphql` dependencies optional.

Installing with `npm install --no-optional` should hopefully install without those, but then `sd_notify_promise` won't get installed if we do that.

### CODE REVIEW

**Comment by auscompgeek** [comment]
This blocks #8.

**Review by thewrongjames — APPROVED** [review]
@auscompgeek To be honest, I do not understand the structure of the API codebase well enough to feel I can give a particularly high quality review here. Presuming that I remain sysadmin (I'm running, but, you never know), I will need to improve my understanding at some point, but, we probably shouldn't wait for that. I am happy to trust you on this, but if there is anything in particular we will like me to check I'll unapprove and do that first.

Sorry.

**Comment by auscompgeek** [comment]
Honestly I was largely just following the NestJS migration guides here. Might be worth checking that all the endpoints still work as expected; I wasn't very thorough in testing.

**Comment by thewrongjames** [comment]
Okay, yeah, I'll try to go through them. Won't get to them tonight, but perhaps over the rest of the week.

**Comment by auscompgeek** [comment]
Heh, a couple of unrelated changes I had in my working tree snuck into this PR. I'll probably separate those into different PRs.

**Comment by thewrongjames** [comment]
Made redundant by #26.

**Pull request closed without merging**
